table: fact_events
type: fact
grain: one row per user event
description: User clickstream events

columns:
  - name: event_id
    type: string
    nullable: false

  - name: user_id
    type: string

  - name: event_type
    type: string

  - name: product_id
    type: string

  - name: event_timestamp
    type: timestamp

  - name: ingestion_timestamp
    type: timestamp
